package com.genflow.genflowai.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;
import java.util.Map;

/**
 * Response body from the genflowai-agent:
 * POST /api/v1/queries/nl-to-sql
 *
 * Maps to the Python GeospatialQueryResponse Pydantic model.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class AgentQueryResponse {

    /** Unique identifier for this agent request (UUID generated by agent) */
    @JsonProperty("request_id")
    private String requestId;

    /** The SQL generation result including the query, safety flag, and agent logs */
    @JsonProperty("result")
    private AgentSqlResult result;

    /**
     * Path to the generated shapefile zip (relative to agent base URL).
     * Values: "PENDING" | "/api/v1/queries/download/<filename>.zip" | "UNSAFE_SQL"
     */
    @JsonProperty("shapefile_path")
    private String shapefilePath;

    // ---- Getters ----
    public String getRequestId() { return requestId; }
    public AgentSqlResult getResult() { return result; }
    public String getShapefilePath() { return shapefilePath; }

    // ---- Nested: SQL result ----

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class AgentSqlResult {
        @JsonProperty("sql")
        private String sql;

        @JsonProperty("is_safe")
        private boolean isSafe;

        @JsonProperty("reasoning")
        private String reasoning;

        @JsonProperty("agent_logs")
        private List<Map<String, String>> agentLogs;

        public String getSql() { return sql; }
        public boolean isSafe() { return isSafe; }
        public String getReasoning() { return reasoning; }
        public List<Map<String, String>> getAgentLogs() { return agentLogs; }
    }
}
